# Generated by Django 5.1.4 on 2024-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag_alter_imageupload_original_category"),
        ("music", "0002_album_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["slug"], name="music_album_slug_eeb8f6_idx"),
        ),
    ]
