[project]
name = "bozbalci-blog"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.5",
    "django-cors-headers>=4.6.0",
    "django-debug-toolbar>=5.0.1",
    "django-ninja>=1.3.0",
    "django-storages[s3]>=1.14.4",
    "django-vite>=3.0.6",
    "exifread>=3.0.0",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.5",
    "mistune>=3.1.0",
    "pillow>=11.1.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
    "sentry-sdk[django]>=2.22.0",
    "whitenoise>=6.8.2",
]

[dependency-groups]
dev = [
    "colorama>=0.4.6",
    "fabric>=3.2.2",
    "ruff>=0.9.1",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
