# Generated by Django 5.1.4 on 2024-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="removed_from_s3",
            field=models.BooleanField(default=False),
        ),
    ]
