# Generated by Django 5.1.4 on 2024-12-20 00:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_imageupload_original_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="original",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image from your computer.",
                null=True,
                upload_to=core.models.year_month_directory,
            ),
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.year_month_directory_thumb
            ),
        ),
    ]
