# Generated by Django 5.2.1 on 2025-05-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial_v2"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="key",
            field=models.SlugField(),
        ),
    ]
