# Generated by Django 5.1.4 on 2024-12-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_customflatpage_options_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
