# Generated by Django 5.2.1 on 2025-05-22 00:15

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_menu_locale_menu_translation_key_alter_menu_key"),
    ]

    operations = [BootstrapTranslatableModel("blog.Menu")]
