# Generated by Django 5.1.4 on 2024-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
