# Generated by Django 5.2.1 on 2025-05-25 00:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_nowpostpreamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('blockquote', 0), ('paragraph', 1), ('image', 2), ('captioned_image', 4), ('code', 7), ('details', 11), ('image_carousel', 13)], blank=True, block_lookup={0: ('wagtail.blocks.BlockQuoteBlock', (), {}), 1: ('wagtail_footnotes.blocks.RichTextBlockWithFootnotes', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'footnotes']}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Plain text'), ('bash', 'Bash/Shell'), ('python', 'Python')], 'help_text': 'Language for syntax highlighting', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text shown in the summary', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StreamBlock', [[('paragraph', 9), ('code', 7)]], {}), 11: ('wagtail.blocks.StructBlock', [[('summary', 8), ('details', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (4,), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('images', 12)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='body',
            field=wagtail.fields.StreamField([('blockquote', 0), ('paragraph', 1), ('image', 2), ('captioned_image', 4), ('code', 7), ('details', 11), ('image_carousel', 13)], blank=True, block_lookup={0: ('wagtail.blocks.BlockQuoteBlock', (), {}), 1: ('wagtail_footnotes.blocks.RichTextBlockWithFootnotes', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'footnotes']}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Plain text'), ('bash', 'Bash/Shell'), ('python', 'Python')], 'help_text': 'Language for syntax highlighting', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text shown in the summary', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StreamBlock', [[('paragraph', 9), ('code', 7)]], {}), 11: ('wagtail.blocks.StructBlock', [[('summary', 8), ('details', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (4,), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('images', 12)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='nowpostpage',
            name='body',
            field=wagtail.fields.StreamField([('blockquote', 0), ('paragraph', 1), ('image', 2), ('captioned_image', 4), ('code', 7), ('details', 11), ('image_carousel', 13)], blank=True, block_lookup={0: ('wagtail.blocks.BlockQuoteBlock', (), {}), 1: ('wagtail_footnotes.blocks.RichTextBlockWithFootnotes', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'footnotes']}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Plain text'), ('bash', 'Bash/Shell'), ('python', 'Python')], 'help_text': 'Language for syntax highlighting', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text shown in the summary', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StreamBlock', [[('paragraph', 9), ('code', 7)]], {}), 11: ('wagtail.blocks.StructBlock', [[('summary', 8), ('details', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (4,), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('images', 12)]], {})}, null=True),
        ),
    ]
