# Generated by Django 5.2 on 2025-05-09 21:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_nowindexpage_nowpostpage_thenindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0)],
                block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})},
            ),
        ),
    ]
