# Generated by Django 5.2 on 2025-05-09 21:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_blogpostpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("blockquote", 0), ("paragraph", 1)],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
    ]
