# Generated by Django 5.2 on 2025-05-09 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_flatpage_body_stream"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flatpage",
            name="body",
        ),
    ]
