# Generated by Django 5.2 on 2025-05-09 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_remove_flatpage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flatpage",
            old_name="body_stream",
            new_name="body",
        ),
    ]
