# Generated by Django 5.2 on 2025-05-09 21:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_rename_body_stream_flatpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="nowpostpage",
            name="body_stream",
            field=wagtail.fields.StreamField(
                [("blockquote", 0), ("paragraph", 1), ("image", 2), ("code", 5)],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
