# Generated by Django 5.2 on 2025-05-09 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_nowpostpage_body_stream"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nowpostpage",
            name="body",
        ),
    ]
