# Generated by Django 5.2 on 2025-05-09 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_remove_nowpostpage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nowpostpage",
            old_name="body_stream",
            new_name="body",
        ),
    ]
