# Generated by Django 5.2 on 2025-05-10 22:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_alter_flatpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("blockquote", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("code", 5),
                    ("details", 8),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text shown in the summary", "required": True},
                    ),
                    7: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("summary", 6), ("details", 7)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
