# Generated by Django 5.2 on 2025-05-10 23:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_alter_blogpostpage_body_alter_flatpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("blockquote", 0), ("paragraph", 1), ("image", 2), ("code", 5)],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    1: ("wagtail_footnotes.blocks.RichTextBlockWithFootnotes", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Plain text"),
                                ("bash", "Bash/Shell"),
                                ("python", "Python"),
                            ],
                            "help_text": "Language for syntax highlighting",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="flatpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("blockquote", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("code", 5),
                    ("details", 9),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    1: ("wagtail_footnotes.blocks.RichTextBlockWithFootnotes", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Plain text"),
                                ("bash", "Bash/Shell"),
                                ("python", "Python"),
                            ],
                            "help_text": "Language for syntax highlighting",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text shown in the summary", "required": True},
                    ),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 7), ("code", 5)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("summary", 6), ("details", 8)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nowpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("blockquote", 0), ("paragraph", 1), ("image", 2), ("code", 5)],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    1: ("wagtail_footnotes.blocks.RichTextBlockWithFootnotes", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Plain text"),
                                ("bash", "Bash/Shell"),
                                ("python", "Python"),
                            ],
                            "help_text": "Language for syntax highlighting",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
