# Generated by Django 5.2.1 on 2025-05-11 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0029_alter_blogpostpage_body_alter_flatpage_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomFlatPage",
        ),
    ]
