# Generated by Django 5.2.1 on 2025-05-11 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_delete_customflatpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
