# Generated by Django 5.2.1 on 2025-05-11 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0031_remove_post_categories_remove_post_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
