# Generated by Django 5.1.4 on 2024-12-17 21:10
import posixpath
from datetime import datetime

from django.db import migrations, models


# noinspection DuplicatedCode
def year_month_directory(instance, filename):
    """
    Function to generate upload path in the format /year/month/filename
    """
    current_date = datetime.now()
    year = current_date.strftime("%Y")
    month = current_date.strftime("%m")
    return posixpath.join(year, month, filename)


def year_month_directory_thumb(instance, filename):
    current_date = datetime.now()
    year = current_date.strftime("%Y")
    month = current_date.strftime("%m")
    return posixpath.join(year, month, "thumb", filename)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tag_alter_imageupload_original_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="original",
            field=models.ImageField(
                blank=True, null=True, upload_to=year_month_directory
            ),
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=year_month_directory_thumb
            ),
        ),
    ]
