# Generated by Django 5.1.4 on 2024-12-17 21:10

import notcms.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag_alter_imageupload_original_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="original",
            field=models.ImageField(
                blank=True, null=True, upload_to=notcms.core.models.year_month_directory
            ),
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=notcms.core.models.year_month_directory
            ),
        ),
    ]
