# Generated by Django 5.1.5 on 2025-03-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_feature_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkdownSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
