# Generated by Django 5.1.5 on 2025-03-04 16:26
import textwrap

from django.db import migrations


def populate_initial_markdown_snippets(apps, schema_editor):
    MarkdownSnippet = apps.get_model("core", "MarkdownSnippet")

    homepage_snippet = MarkdownSnippet(
        slug="homepage",
        content=textwrap.dedent("""
    Welcome to [*NotCMS*](https://github.com/bozbalci/bozbalci-blog) – my
    roll-your-own WordPress clone built in Django.
    
    This part of the page is a markdown snippet retrieved from the database.
    
    You can edit it in the Django admin panel.
    """),
    )

    homepage_snippet.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_markdownsnippet"),
    ]

    operations = [
        migrations.RunPython(populate_initial_markdown_snippets),
    ]
