# Generated by Django 5.2.1 on 2025-05-11 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_auto_20250304_1626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="ImageUpload",
        ),
        migrations.DeleteModel(
            name="MarkdownSnippet",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
