# Generated by Django 5.1.4 on 2024-12-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
                ("thumbnail_url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("exif", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
