# Generated by Django 5.2.1 on 2025-05-11 18:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("photo", "0001_initial"),
        ("photo", "0002_alter_photo_id"),
        ("photo", "0003_remove_photo_image_url_remove_photo_thumbnail_url_and_more"),
        ("photo", "0004_remove_photo_s3_image_path_photo_image"),
        ("photo", "0005_photo_categories_photo_tags"),
        ("photo", "0006_photoalbum_photo_albums"),
        ("photo", "0007_photopage"),
        ("photo", "0008_photogalleryindexpage"),
        ("photo", "0009_alter_photopage_image"),
        ("photo", "0010_photopage_exif_aperture_photopage_exif_focal_length_and_more"),
        ("photo", "0011_rename_exif_taken_at_photopage_exif_shot_at"),
        ("photo", "0012_remove_photopage_exif"),
        ("photo", "0013_photoalbumpage_photopage_albums"),
        ("photo", "0014_alter_photopage_albums"),
        ("photo", "0015_remove_photo_albums_delete_photoalbum"),
        ("photo", "0016_delete_photo"),
    ]

    dependencies = [
        ("core", "0001_initial"),
        ("core", "0003_tag_alter_imageupload_original_category"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoGalleryIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="PhotoAlbumPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PhotoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                    ),
                ),
                ("exif_aperture", models.CharField(blank=True, max_length=255)),
                ("exif_focal_length", models.CharField(blank=True, max_length=255)),
                ("exif_iso", models.CharField(blank=True, max_length=255)),
                ("exif_lens", models.CharField(blank=True, max_length=255)),
                ("exif_make", models.CharField(blank=True, max_length=255)),
                ("exif_model", models.CharField(blank=True, max_length=255)),
                ("exif_shutter_speed", models.CharField(blank=True, max_length=255)),
                ("exif_shot_at", models.DateTimeField(blank=True, null=True)),
                (
                    "albums",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="photos", to="photo.photoalbumpage"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
