# Generated by Django 5.1.4 on 2024-12-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
