# Generated by Django 5.1.4 on 2024-12-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("photo", "0003_remove_photo_image_url_remove_photo_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="s3_image_path",
        ),
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.imageupload",
            ),
        ),
    ]
