# Generated by Django 5.2.1 on 2025-11-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photopage_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopage',
            name='include_in_camera_roll',
            field=models.BooleanField(default=True),
        ),
    ]
