# Generated by Django 5.1.4 on 2024-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag_alter_imageupload_original_category"),
        ("photo", "0004_remove_photo_s3_image_path_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="categories",
            field=models.ManyToManyField(blank=True, to="core.category"),
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
    ]
