# Generated by Django 5.2.1 on 2025-11-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photopage_include_in_camera_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopage',
            name='albums',
        ),
    ]
