# Generated by Django 5.1.4 on 2024-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0005_photo_categories_photo_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="photo",
            name="albums",
            field=models.ManyToManyField(blank=True, to="photo.photoalbum"),
        ),
    ]
