# Generated by Django 5.2 on 2025-05-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0009_alter_photopage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopage",
            name="exif_aperture",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_focal_length",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_iso",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_lens",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_make",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_shutter_speed",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="photopage",
            name="exif_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
