# Generated by Django 5.2 on 2025-05-09 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0010_photopage_exif_aperture_photopage_exif_focal_length_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photopage",
            old_name="exif_taken_at",
            new_name="exif_shot_at",
        ),
    ]
