# Generated by Django 5.2 on 2025-05-09 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0011_rename_exif_taken_at_photopage_exif_shot_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photopage",
            name="exif",
        ),
    ]
