# Generated by Django 5.2 on 2025-05-09 23:59

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0013_photoalbumpage_photopage_albums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photopage",
            name="albums",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="photos", to="photo.photoalbumpage"
            ),
        ),
    ]
