# Generated by Django 5.2.1 on 2025-05-11 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0014_alter_photopage_albums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="albums",
        ),
        migrations.DeleteModel(
            name="PhotoAlbum",
        ),
    ]
