# Generated by Django 5.2.1 on 2025-05-11 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0015_remove_photo_albums_delete_photoalbum"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
