# Generated by Django 5.2.1 on 2025-05-11 18:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("music", "0001_initial"),
        ("music", "0002_album_slug"),
        ("music", "0003_album_year_album_music_album_slug_eeb8f6_idx"),
        ("music", "0004_album_music_album_rating_a86dad_idx"),
        ("music", "0005_lastfmsettings"),
        ("music", "0006_albumpage"),
        ("music", "0007_musiccollectionindexpage"),
        ("music", "0008_delete_album"),
    ]

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastfmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("api_secret", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("show_widget_in_footer", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AlbumPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("openscrobbler_url", models.URLField(blank=True, null=True)),
                ("discogs_url", models.URLField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("review", wagtail.fields.RichTextField(blank=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MusicCollectionIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
