# Generated by Django 5.1.4 on 2024-12-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_imageupload_original_and_more"),
        ("music", "0003_album_year_album_music_album_slug_eeb8f6_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["rating"], name="music_album_rating_a86dad_idx"),
        ),
    ]
