# Generated by Django 5.2 on 2025-05-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_album_music_album_rating_a86dad_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastfmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("api_secret", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("show_widget_in_footer", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
