# Generated by Django 5.2 on 2025-05-09 02:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_lastfmsettings"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("openscrobbler_url", models.URLField(blank=True, null=True)),
                ("discogs_url", models.URLField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("review", wagtail.fields.RichTextField(blank=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
