# Generated by Django 5.2.1 on 2025-05-11 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_musiccollectionindexpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Album",
        ),
    ]
